<?php

namespace Plugin\ApplePayStripePlugin\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderStripeCharge
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStripeCharge extends EntityRepository
{
}
